name: commride_mobile
description: CommRide rider-first touring coordination mobile application.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  http: ^1.6.0
  geolocator: ^14.0.3
  geolocator_android: ^5.0.3
  geolocator_apple: ^2.3.14
  maplibre_gl: 0.27.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
